# Generated by Django 5.2.15 on 2026-06-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeembedding',
            name='model',
            field=models.CharField(default='gemini-embedding-001', max_length=100),
        ),
    ]
