# Generated by Django 5.2.15 on 2026-06-23 20:10

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_alter_resumeembedding_model'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE resume_embeddings DROP COLUMN IF EXISTS embedding;
                        ALTER TABLE resume_embeddings ADD COLUMN embedding vector(768);
                    """,
                    reverse_sql="""
                        ALTER TABLE resume_embeddings DROP COLUMN IF EXISTS embedding;
                        ALTER TABLE resume_embeddings ADD COLUMN embedding jsonb DEFAULT '[]'::jsonb;
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        CREATE INDEX IF NOT EXISTS resume_embedding_hnsw_idx
                        ON resume_embeddings USING hnsw (embedding vector_cosine_ops);
                    """,
                    reverse_sql="DROP INDEX IF EXISTS resume_embedding_hnsw_idx;",
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='resumeembedding',
                    name='embedding',
                    field=pgvector.django.vector.VectorField(dimensions=768),
                ),
                migrations.AddIndex(
                    model_name='resumeembedding',
                    index=pgvector.django.indexes.HnswIndex(
                        fields=['embedding'],
                        name='resume_embedding_hnsw_idx',
                        opclasses=['vector_cosine_ops'],
                    ),
                ),
            ],
        ),
    ]
